# Generated by Django 3.2.7 on 2022-07-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0033_auto_20220525_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mssg', models.TextField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('victims_fname', models.CharField(max_length=20)),
                ('victims_lname', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=500)),
                ('subject', models.TextField(max_length=50)),
                ('idproof_number', models.CharField(max_length=30)),
                ('idprooof', models.FileField(upload_to='data/id/')),
                ('vedio', models.FileField(upload_to='data/vids/')),
                ('image', models.FileField(upload_to='data/imgs/')),
                ('message', models.TextField(max_length=50)),
                ('gender', models.CharField(default='NA', max_length=50, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
