# Generated by Django 3.2.7 on 2022-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_emergencycontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='profession',
            field=models.CharField(default='', max_length=30),
        ),
    ]
