# Generated by Django 3.2.7 on 2022-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_profiledetails_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='uemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
