# Generated by Django 3.2.7 on 2022-05-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_alter_profiledetails_uemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='contactusmodel',
        ),
        migrations.RemoveField(
            model_name='emergencycontacts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.DeleteModel(
            name='EmergencyContacts',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileDetails',
        ),
    ]
